{
 "title": "nifi_health_performance_view",
 "description": "Monitoring the actual flowfiles, processors, success/failure, and backpressure in NiFi pipeline.",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Pipeline: Rate of failure per min",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nifi_amount_items_input{component_name=\"failure_conn\"}[1m])) * 60\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[QB] Queue Usage %",
   "type": "gauge",
   "description": "Overall utilization across all connections",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 *\nsum(nifi_amount_items_queued{component_type=\"Connection\"})\n/\nsum(nifi_backpressure_object_threshold{component_type=\"Connection\"})",
     "legendFormat": "{{destination_name}}"
    }
   ]
  },
  {
   "title": "[QB] FlowFiles Queued",
   "type": "stat",
   "description": "Queue & Backpressure",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nifi_amount_items_queued{component_type=\"Connection\"}",
     "legendFormat": "{{destination_name}}"
    }
   ]
  },
  {
   "title": "[QB] Backpressure Status",
   "type": "table",
   "description": "Queue & Backpressure:",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "targets": [
    { "expr": "nifi_backpressure_enabled", "legendFormat": "{{component_name}}" }
   ]
  },
  {
   "title": "[DV] Bytes Written per second",
   "type": "timeseries",
   "description": "Data Volume",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(nifi_amount_bytes_written[5m])",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "[DV] Bytes Read per second",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(nifi_amount_bytes_read[5m])",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "[DV] NiFi Data Output Rate/processor",
   "type": "timeseries",
   "description": "How many bytes per second a NiFi processor / outputs.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(nifi_size_content_output_total{component_type=\"Processor\"}[1m])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "[PH] Average Lineage Duration",
   "type": "timeseries",
   "description": "Processor Health\nProcessing latency",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "nifi_average_lineage_duration", "legendFormat": "{{component_name}}" }
   ]
  },
  {
   "title": "[FF] FlowFiles Sent per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(nifi_amount_flowfiles_sent[1m])",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "[FF] FlowFiles Received per second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(nifi_amount_flowfiles_received[1m])",
     "legendFormat": "{{component_name}}"
    }
   ]
  },
  {
   "title": "[PH] Active Threads",
   "type": "timeseries",
   "description": "Processor Health\nTrend per processor: NiFi internal “CPU-like” metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "nifi_amount_threads_active{component_type=\"Processor\"}",
     "legendFormat": "{{component_name}}"
    }
   ]
  }
 ]
}